In [2]:
#sum of elements in array
import numpy as np
arr = np.array([1,4,7,9])
s = sum(arr)
s

21

In [10]:
import numpy as np
arr = np.array([1,4,7,9])
sum1 = 0
for i in arr:
    sum1 = sum1 + i
    
print(sum1)    

21


In [28]:
#1-D array input taken from the user

array = []
n = int(input("enter number of element"))
for i in range(0,n):
    x = int(input())
    array.append(x)
print(array)

enter number of element4
5
7
3
8
[5, 7, 3, 8]


In [35]:
#2-D array input taken from the user

rows = int(input("enter no of rows:"))
columns = int(input("enter no of columns:"))
matrix = []


for i in range(rows):
    a = []
    for j in range(columns):
        a.append(int(input()))
    matrix.append(a)

for i in range(rows):
    for j in range(columns):
        print(matrix[i][j],end = " ")
    print()

enter no of rows:2
enter no of columns:3
1
2
3
4
5
6
1 2 3 
4 5 6 


In [15]:
#largest element in array
arr = [10, 324, 45, 90, 98]
max = arr[0]
for i in range(0,len(arr)):
    if arr[i] > max:
        max = arr[i]
    
print(max,"is the largest element")
    
    

324 is the largest element


In [14]:
def largest(arr,n):
    max = arr[0]
    
    for i in range(1,n):
        if arr[i] > max:
            max = arr[i]
    return max
arr = [10, 324, 45, 90, 9808]
n = len(arr)
res = largest(arr,n)
print(res,"is largest in array")

9808 is largest in array


In [16]:
#Python program using the List slicing approach to rotate the array
def rotate(arr,n,d):
    arr[:] = arr[d:n]+arr[0:d]
    return arr
arr = [1,2,3,4,5,6]
res = rotate(arr,len(arr),2)
print(res)

[3, 4, 5, 6, 1, 2]


In [1]:
# Python program to split array and move first part to end.
def splitArr(a, n, k):
    b = a[:k]
    return (a[k::]+b[::])

arr = [12, 10, 5, 6, 52, 36]
n = len(arr)
position = 2
arr = splitArr(arr, n, position)
for i in range(0, n):
    print(arr[i], end = ' ')

5 6 52 36 12 10 

In [1]:
#python progrma for find the remainder of array multiplication divided by n

from functools import reduce
def find_remainder(arr,n):
    sum1 = reduce(lambda x,y:x*y,arr)
    remainder = sum1/n
    return(remainder)
arr = [1,2,3,4,5]
n = 2
res = find_remainder(arr,n)
print(res)

60.0


In [10]:
arr = [1,2,3,4,5]
print(arr[:])

[1, 2, 3, 4]


In [22]:
def allFib(n):
    for i in range(n):
        print(str(i)+":" + str(fib(i)))

def fib(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    return fib(n-1) + fib(n-2)


allFib(10)


0:0
1:1
2:1
3:2
4:3
5:5
6:8
7:13
8:21
9:34


In [4]:
def powersOf2(n):
    
    if n < 1:
        return 0
    elif n == 1:
        
        return 1
    else:
        prev = powersOf2(int(n/2))
        # print("prev:"+str(prev))
        print(prev)
        curr = prev*2
        
        return curr

powersOf2(5)

1
2


4

In [1]:
#creation of two dimensional array

import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)

newTwoDArray = np.insert(twoDArray, 1, [[1,2,3,4]], axis=1)
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[11  1 15 10  6]
 [10  2 14 11  5]
 [12  3 17 12  8]
 [15  4 18 14  9]]


In [9]:
#Acessing elements from the two dimensional array
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)

def acessele(array,rowindex,colindex):
    if rowindex >= len(array) and colindex >= len(array):
        print("incorrect index")
    else:
        print(array[rowindex][colindex])
   
acessele(twoDArray,1,2)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11


In [10]:
#traversing through two dimensional array

import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(twoDArray)

def traverse(array):
    for i in range(len(array)):
        for j in range(len(array)):
            print(array[i][j])
traverse(twoDArray)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


In [22]:
import numpy as np

t_a = np.array([[8,9,3,0,10],[3,5,17,1,1],[2,8,6,23,1],[15,7,3,2,9],[6,14,2,6,0]])
print(t_a)

row_sum = 0
column_sum = 0

print("\nrow_sum:")
for i in range(len(t_a)):
    for j in range(len(t_a)):
        row_sum = row_sum + t_a[i][j]
    print(row_sum,end =" ")
    row_sum = 0
    
print("\ncolumn_sum:")    
for j in range(len(t_a)):
    for i in range(len(t_a)):
        column_sum = column_sum + t_a[i][j]
    print(column_sum,end = " ")
    column_sum = 0    

[[ 8  9  3  0 10]
 [ 3  5 17  1  1]
 [ 2  8  6 23  1]
 [15  7  3  2  9]
 [ 6 14  2  6  0]]

row_sum:
30 27 40 36 28 
column_sum:
34 43 31 32 21 

In [10]:
#Diagonal Sum
"""Example 1:
Input: mat = [[1,2,3],
              [4,5,6],
              [7,8,9]]
Output: 25
Explanation: Diagonals sum: 1 + 5 + 9 + 3 + 7 = 25
Notice that element mat[1][1] = 5 is counted only once.

Example 2:
Input: mat = [[1,1,1,1],
              [1,1,1,1],
              [1,1,1,1],
              [1,1,1,1]]
Output: 8

Example 3:
Input: mat = [[5]]
Output: 5"""
def diagonalSum(mat):
    n = len(mat)
    total_sum = 0
    
    for i in range(n):
        total_sum = total_sum + mat[i][i]         #main diagonal
        total_sum = total_sum + mat[i][n-i-1]     #anti-diagonal
    
    # If n is odd, subtract the middle element which was added twice
    if n%2==1:
        total_sum = total_sum - mat[n//2][n//2]
        
    return total_sum
mat = [[1,2,3],[4,5,6],[7,8,9]]
diagonalSum(mat)

25

In [8]:
# printing diagonal indices

import numpy as np
def print_diagonal_indices(n, m):
    mat = [[0]*(n) for _ in range(m)]
    print(np.array(mat))
    
    # Print main diagonal and diagonals above it
    for d in range(m):
        diagonal = []
        for i in range(min(n, m - d)):
            diagonal.append((i, i + d))
        print(f"Diagonal starting at (0, {d}): {diagonal}")
    
    # Print diagonals below the main diagonal
    for d in range(1, n):
        diagonal = []
        for i in range(min(m, n - d)):
            diagonal.append((i + d, i))
        print(f"Diagonal starting at ({d}, 0): {diagonal}")

# Example usage:
print_diagonal_indices(3, 3)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Diagonal starting at (0, 0): [(0, 0), (1, 1), (2, 2)]
Diagonal starting at (0, 1): [(0, 1), (1, 2)]
Diagonal starting at (0, 2): [(0, 2)]
Diagonal starting at (1, 0): [(1, 0), (2, 1)]
Diagonal starting at (2, 0): [(2, 0)]


In [5]:
#matrix multiplication
import numpy as np
a = np.array([[1,2,1],[2,3,5]])  #2*3 matrix
b = np.array([[1,2,0],[4,2,1],[1,1,1]])  #3*3 matrix

print(a)
print(b)

result = [[0,0,0],[0,0,0]]

for i in range(len(a)):  #rows in x
    for j in range(len(b[0])):  # cols in y
        for k in range(len(b)): # rows in y
            result[i][j] = result[i][j] + a[i][k] * b[k][j]
for r in result:
    print(r)

[[1 2 1]
 [2 3 5]]
[[1 2 0]
 [4 2 1]
 [1 1 1]]
[10, 7, 3]
[19, 15, 8]


In [2]:
#matrix addition
a = [[1,2,3],[4,5,6],[7,8,9]]  #3*3 matrix
b = [[3,4,5],[7,8,6],[1,2,5]]  #3*3 matrix

result = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(a)):
    for j in range(len(b[0])):
        result[i][j] = a[i][j] + b[i][j]
for r in result:
    print(r)
    print()

[4, 6, 8]

[11, 13, 12]

[8, 10, 14]



In [5]:
import numpy as np

In [8]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [13]:
x = 9
squares = []
for i in range(x):
    squares.append(i**2)
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64]


In [17]:
squares = []
n = 10
x = [i**2 for i in range(10)]
squares.append(x)
squares

[[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]]

In [18]:
func = lambda x,y : x+y
x = func(10,30)
print(x)

40


In [7]:
import numpy as np

x = np.array([[10,20,30],[40,50,60],[70,80,90]])
for i in range(len(x)):
    for j in range(len(x[i])):
        print(x[i][j],end = " ")
    print()
print(x)

for i in range(len(x)):
    for j in range(len(x)):
        print(x[i][j])
    print()
    
    


10 20 30 
40 50 60 
70 80 90 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30

40
50
60

70
80
90



In [12]:
# transpose of matrix
import numpy as np

x = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(x)

res = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        res[j][i] = x[i][j]
for i in range(len(res)):
    for j in range(len(res)):
        print(res[i][j],end = " ")
    print()

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10 40 70 
20 50 80 
30 60 90 


In [1]:
# changing the matrix corner elements

m = int(input('enter number of rows'))
n = int(input('enter number of columns'))
mat = []

for i in range(m):
    a = []
    for j in range(n):
        a.append(int(input()))
    mat.append(a)
for r in mat:
    print(r)
    
rows = len(mat)
cols = len(mat[0])

mat[0][0] = 0
mat[0][cols-1] = 0
mat[rows-1][0] = 0
mat[rows-1][cols-1] = 0

for s in mat:
    print(s)

enter number of rows3
enter number of columns3
1
2
3
4
5
6
7
8
9
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[0, 2, 0]
[4, 5, 6]
[0, 8, 0]


In [2]:
arr = [4,7,9,2,2,5,7,8,9,3,3]
res = []
for i in range(len(arr)):
    if arr[i] not in res:
        res.append(arr[i])
print(res)
print(sorted(res))

[4, 7, 9, 2, 5, 8, 3]
[2, 3, 4, 5, 7, 8, 9]


In [2]:
arr = list(map(lambda x:x*x, list(map(int, input().split(" ")))))
print(arr)

1 2 3 4 5 6 7 8 9 0
[1, 4, 9, 16, 25, 36, 49, 64, 81, 0]


In [4]:
def iseven(n):
    if n%2 == 0:
        return True
    else:
        return False
l = [1,2,3,4,5,5,6,6,7,7,8]
res = list(filter(iseven,l))
print(res)

[2, 4, 6, 6, 8]


In [5]:
l = [1,2,3,4,5,5,6,6,7,7,8]
res = list(filter(lambda x:x%2==0,l))
print(res)

[2, 4, 6, 6, 8]


In [6]:
def double(x):
    return x**2
l = [1,2,3,4,5,6,7,8,9]
res = list(map(double,l))
print(res)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [7]:
l = [1,2,3,4,5,6,7,8,9]
res = list(map(lambda x:x**2,l))
print(res)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [4]:
#matrix multiplication
a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2],[4,5],[6,7]]

c = [[0,0],[0,0],[0,0]]

for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j] = c[i][j] + a[i][k] * b[k][j]
for i in c:
    print(x)

[27, 33]
[60, 75]
[93, 117]


In [3]:
b = [[1,2],[4,5],[6,7]]
x = b[0][1]
x

2

In [8]:
#search rowwise and column wise elements in a matrix
import numpy as np
arr = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(arr)

def acess(arr,r,c):
    if r >= len(arr) and c >= len(arr):
        return "incorrect data"
    else:
        res = arr[r][c]
    return res
arr = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
out = acess(arr,1,1)
print(out)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
14


In [18]:
import numpy as np
def search_2d(a,x):
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i][j] == x:
                print("element is found at",i,j)
a = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9] ])
print(a)
x = int(input("enter which elements cordinats u want"))
res = search_2d(a,x)
print(res)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
enter which elements cordinats u want14
element is found at 1 1
element is found at 3 2
None


In [1]:
seq = ['apple','banana','apple','orange','banana','pear','banana','pear','banana']
dict1 = {}
for word in seq:
    if word not in dict1:
        dict1[word] = 0
    dict1[word] += 1

sorted_freq = sorted(dict1.items())
print(sorted_freq)

[('apple', 3), ('banana', 5), ('orange', 2), ('pear', 3)]


In [15]:
'''Given an array with k distinct elements, write a function to return all elements that have at least two elements greater
than themselves in the same array:

array = [2,3,9,7,6]
    
#Your function should return:   

[2,3,6]'''
    
def fun(arr):
    arr.sort()
    print(arr)
    res = []
    
    for i in range(0,len(arr)//2+1):
        if arr[i] < arr[i+1] and arr[i]<arr[i+2]:
            res.append(arr[i])
    return res
    

arr = [3,7,1,8,9,4]
fun(arr)

[1, 3, 4, 7, 8, 9]


[1, 3, 4, 7]

In [16]:
def fun(arr):
    arr.sort()
    res = []
    
    for i in range(len(arr)-2):
        res.append(arr[i])
    return res
    
nums = [3,7,1,8,9,4]
fun(arr)

[1, 3, 4, 7]

In [3]:
"""Given a sorted (in increasing order) array of positive numbers, can you find the smallest positive integer that cannot be
represented as a sum of elements from the array?

Input:  arr[] = [1, 3, 6, 10, 11, 15]
Output: 2

Input:  arr[] = [1, 1, 1, 1]
Output: 5
    
Input:  arr[] = [1, 1, 3, 4]
Output: 10"""

def fun(arr):
    res = 1  # 1 is the smallest positive integer
    
    for num in arr:
        if num>res:  # If num is greater than res, then we found the gap
            break
        else:
            res = res + num
    return res

arr = [1, 3, 6, 10, 11, 15]
fun(arr)

2

In [6]:
"""Given an array of n distinct elements, can you find all the triplet combinations that sum to zero?

Input: [0, -1, 2, -3, 1]
Output: 

0 -1 1

2 -3 1
    

Input: [1, -2, 1, 0, 5]

Output: 1 -2  1"""

def _3sum(nums):
    n = len(nums)
    nums.sort()
    triplets = []
    
    for i in range(n-2):
        if i>0 and nums[i] == nums[i-1]:
            continue
        left = i+1
        right = n-1
        
        while left<right:
            total = nums[i]+nums[left]+nums[right]
            
            if total<0:
                left = left+1
            elif total>0:
                right = right-1
            else:
                triplets.append([nums[i],nums[left],nums[right]])
                
                while left<right and nums[left] == nums[left+1]:
                    left = left +1
                while left<right and nums[right] == nums[right-1]:
                    right = right -1
                
                left = left+1
                right = right-1
    return triplets


nums = [1, -2, 1, 0, 5]
_3sum(nums)

[[-2, 1, 1]]

In [8]:
"""Given an array of integers, can you write a function that returns "True" if there is a triplet (a, b, c) within the array 
that satisfies a^2 + b^2 = c^2?

Input: arr[] = [3, 1, 4, 6, 5]
Output: True
#There is a Pythagorean triplet (3, 4, 5) that exists in the input array.
    
Input: arr[] = {10, 4, 6, 12, 5}
Output: False
#There is no Pythagorean triplet that exists in the input array."""

def fun(nums):
    n = len(nums)
    nums.sort()
    
    for i in range(n):
        for j in range(i+1,n):
            for k in range(j+1,n):
                a, b, c = nums[i],nums[j], nums[k]
                if c^2 == a^2 + b^2:
                    return (a,b,c)
    return False
    
arr = [3, 1, 4, 6, 5]
fun(arr)

(1, 3, 4)

In [12]:
#Efficient method
def fun(nums):
    n = len(nums)
    squared_values = [i*i for i in nums]
    squared_values.sort()
    
    for i in range(n-1,1,-1):
        c_square = squared_values[i]
        left = 0
        right = i-1
        
        while left<right:
            if squared_values[left] + squared_values[right] == c_square:
                return True
            elif squared_values[left] + squared_values[right] < c_square:
                left += 1
            else:
                right -=1
    return False
arr = [3, 1, 4, 6, 5]
fun(arr)

True