In [ ]:
#Acessing elements in list
"""
shopping = ['bread','eggs','cheese','fruits']
#print(shopping[-1])

#traversing through list

for i in range(len(shopping)):
    print(shopping[i])

#update/insert ele in list
lst = [1,2,3,4,5]
lst[2] = 10
lst[4] = 20
print(lst)

lst.insert(0,30)
lst.append(40)
print(lst)

newlst = [9,99,999]
lst.extend(newlst)
print(lst)

#slicing and deletion of list of elements

lst = ['a','b','h','i','n','a','y']

lst[0:2] = ['A','B']
print(lst[:])

lst.pop()
lst.pop(-1)

del lst[1]

lst.remove('h')
print(lst)


#searching for an element in a list

lst = [10,20,30,40,50,60,70,80,90]
#in method
if 20 in lst:
    print(lst.index(20))
else:
    print("ele is not in list")

#linear search

def linear_Search(list,value):
    for i in list:
        if i == value:
            return list.index(value)
    return "ele is not exist in list"

lst = [10,20,30,40,50,60,70,80,90]
print(linear_Search(lst,100))


#list operations or functions

x = [1,2,3]
y = [4,5,6]
z = x+y
print(z)

x = "abhi"
x = x*3
print(x)



count = 0
total = 0
while(True):    
    inp = input("enter a num:")
    if inp == 'done':
        break
    value = float(inp)
    total = total + value
    count = count + 1
    avg = total/count
print("average",avg)



list1 = list()
while(True):
    inp = input("enter a num:")
    if inp == 'done':
        break
    val = float(inp)
    list1.append(val)
avg = sum(list1)/len(list1)
print(avg)
"""
#how to implement list fro strings

x = "abhinay"
y = list(x)
print(y)

In [3]:
#find missing number from 1 to 100

mylist = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
          29, 30, 31, 32, 33, 34 , 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 
          55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,74, 75, 76, 77, 78, 79, 80,
          81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
def find_missing(list,n):
    sum1 = 100*101/2
    sum2 = sum(list)
    print(sum1-sum2)
find_missing(mylist,100)


35.0


In [8]:
#find all pairs of integers whose sum is equal to given target number

def find_pairs(mylist,target):
    for i in range(len(mylist)):
        for j in range(i+1,len(mylist)):
            if mylist[i] == mylist[j]:
                continue
            elif mylist[i] + mylist[j] == target:
                print(i,j)
list = [1,2,3,2,3,4,5,6]
find_pairs(list,5)

0 5
1 2
1 4
2 3
3 4


In [9]:
x = int(input("enter the element to search:"))
list = [1,2,3,2,3,4,5,6]
for i in range(len(list)):
    if list[i] == x:
        print(i)

enter the element to search:4
5


In [10]:
#search element is present in the list or not

def search(list,num):
    for i in range(len(list)):
        if list[i] == num:
            print(i)
list = [1,2,3,2,3,4,5,6]
search(list,2)

1
3


In [12]:
#find maximum product of two integers in array

def max_product(array):
    maxproduct = 0
    for i in range(len(array)):
        for j in range(i+1,len(array)):
            if array[i]*array[j] > maxproduct:
                maxproduct =  array[i]*array[j]
                pairs = str(array[i])+ "," +str(array[j])
    print(pairs)
    print(maxproduct)
array = [1,2,3,2,3,4,5,6]
max_product(array)
            

5,6
30


In [13]:
#find if a list contains unique elements

def is_unique(array):
    a = []
    for i in array:
        if i in a:
            print(i)
            return False
        else:
            a.append(i)
    return True
array = [1,2,3,2,3,4,5,6]
print(is_unique(array))

2
False


In [4]:
#permutation

def permutation(list1,list2):
    if len(list1) != len(list2):
        return False
    list1.sort()
    list2.sort()
    
    if list1 == list2:
        return True
    else:
        return False
list1 = [5,1,6,9]
list2 = [9,6,5,1]
print(permutation(list1,list2))



True


In [27]:
#rotate matrix
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

def rotatematrix(matrix):
    n = len(matrix)
    for layer in range(n//2):
        first = layer
        last = n-layer-1
    
    for i in range(first,last):
        #save top element
        top = matrix[layer][i]
        #move left element to top
        matrix[layer][i] = matrix[-i-1][layer]
        #move bottom element to left
        matrix[-i-1][layer] = matrix[-layer-1][-i-1]
        #move right to bottom
        matrix[-layer-1][-i-1] = matrix[i][-layer-1]
        #move to top
        matrix[i][-layer-1] = top
    return matrix   

print("$Rotated matrix$")
print(rotatematrix(array))
    


[[1 2 3]
 [4 5 6]
 [7 8 9]]
$Rotated matrix$
[[7 4 1]
 [8 5 2]
 [9 6 3]]
