In [4]:
#1)two sum
#Input: nums = [2,7,11,15], target = 9
#Output: [0,1]

nums = [2,7,11,15]
target = 18

if len(nums)<=0:
    print(False)
dict1={}
for i in range(len(nums)):
    if nums[i] in dict1:
        print(dict1[nums[i]],i)
    else:
        dict1[target-nums[i]]=i

1 2


In [8]:
""""Input: arr[] = {1, 4, 20, 3, 10, 5}, sum = 33
Output: Sum found between indexes 2 and 4
Explanation: Sum of elements between indices 2 and 4 is 20 + 3 + 10 = 33"""

def fun(nums, n, target):
    for i in range(n):
        current_sum = nums[i]
        if current_sum == target:
            print('sum found at index',i)
        else:
            for j in range(i+1,n):
                current_sum = current_sum + nums[j]
                if current_sum == target:
                    print('sum found between indexes',i,'and',j)

nums = [1,4,20,3,10,5]
target = 23
n = len(nums)
fun(nums, n, target)

sum found between indexes 2 and 3


In [2]:
#3)longest substring without repeating the characters

s = "papavvn"
max_length = 0
start = 0
visited = {}

for i in range(len(s)):
    # Check if the character is already visited
    if s[i] in visited and start <= visited[s[i]]:
        # Update the start position
        start = visited[s[i]] + 1
    else:
        # Calculate the current substring length
        max_length = max(max_length, i - start + 1)
      
    # Mark the character as visited
    visited[s[i]] = i
  # Print the length of the longest substring
print(max_length)

3


In [7]:
#longest substring without reepeating characters

s = "length of the longest substring without repeating character"
s1 = 'ababba'
max_length = 0
start = 0
visited = {}
longest_substr = ""

for i in range(len(s)):
    if s[i] in visited and start <= visited[s[i]]:
        start = visited[s[i]] + 1
    else:
        current_length = i-start+1
        if current_length>max_length:
            max_length = current_length
            longest_substr = s[start:i+1]
    visited[s[i]] = i
print(longest_substr)


ubstring w


In [10]:
#560. Subarray Sum Equals K
#Input: nums = [1,1,1], k = 2
#Output: 2

def subarray(nums,k):
    count = 0
    pre_sum = 0
    sum_count = {0:1}
    
    for num in nums:
        pre_sum = pre_sum+num
        
        if pre_sum - k in sum_count:
            count = count + sum_count[pre_sum-k]
            
        if pre_sum in sum_count:
            sum_count[pre_sum]+=1
        else:
            sum_count[pre_sum]=1
    return count
nums = [1,1,1,1,2]
k = 3
res = subarray(nums,k)
print(res)

3


In [5]:
#20. Valid Parentheses
#Input: s = "()"
#Output: true

#Input: s = "()[]{}"
#Output: true

s = "[}"
dict1 =  {')': '(','}': '{',']': '[' }
stack = []

for char in s:
    if char in dict1.values():
        stack.append(char)
    elif char in dict1.keys():
        if stack.pop() != dict1[char]:
            print(False)
#print(stack)
print(len(stack)==0)

False
True


In [1]:
s = "[]"
mapping = {')':'(','}':'{',']':'['}
stack = []

for char in s:
    if char in mapping:
        top_element = stack.pop() if stack else ""
        if mapping[char] != top_element:
            print(mapping[char])
            continue
    else:
        stack.append(char)
        print(stack)
print(len(stack)==0)

['[']
True


In [1]:
#8.Roman to Integer

s = "XIX"

dict1 = {'I':1,'V':5,'X':10,'L':50,'C':100,'D':500,'M':1000}
pre = 0
curr = 0
total = 0

for i in range(len(s)):
    curr = dict1[s[i]]
    if curr > pre:
        total = total + curr - 2*pre
    
    else:
        total = total + curr
    
    pre = curr
print(total)
s = total
y = ord('s')
y

19


115

In [11]:
#53. Maximum Subarray sum
#Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
#Output: 6
#Explanation: The subarray [4,-1,2,1] has the largest sum 6.

def max_subarray(nums): 
    curr_sum = nums[0]
    max_sum = nums[0]
    
    for i in range(1,len(nums)):
        curr_sum = max(nums[i],curr_sum+nums[i])
        max_sum = max(max_sum,curr_sum)
    return max_sum
     
nums = [-2,1,-3,4,-1,2,1,-5,4]
res = max_subarray(nums)
print(res)

6


In [6]:
def max_subarray(nums):
    curr_sum = max_sum = nums[0]
    start = end = s = 0
    
    for i in range(1,len(nums)):
        if nums[i] > curr_sum + nums[i]:
            curr_sum = nums[i]
            s = i
        else:
            curr_sum = curr_sum + nums[i]
    
        if curr_sum > max_sum:
            max_sum = curr_sum
            start = s
            end = i
    return nums[start:end+1], max_sum


nums = [-2,1,-3,4,-1,2,1,-5,4]
res = max_subarray(nums)
print(res)

([4, -1, 2, 1], 6)


In [2]:
#14. Longest Common Prefix
#Input: strs = ["flower","flow","flight"]
#Output: "fl"

def longest_common_prefix(str):
    lcp = ""
    if str is None and len(str) == 0:
        return lcp
    min_len_str = len(str[0])
    for i in range(len(str)):
        min_len_str = min(min_len_str,len(str[i]))
        
    for i in range(0,min_len_str):
        current = str[0][i]
        for j in range(0,len(str)):
            if str[j][i] != current:
                return lcp
        lcp = lcp + current
    return lcp

str = ['flower','flow','flight']
longest_common_prefix(str)

'fl'

In [4]:
def longestCommonPrefix(strs):
    # Longest common prefix string
    lcp = ""
    
    # Base condition
    if strs is None or len(strs) == 0:
        return lcp
    
    # Find the minimum length string from the array
    minimumLength = len(strs[0])
    for i in range(1, len(strs)):
        minimumLength = min(minimumLength, len(strs[i]))
        
    # Loop until the minimum length
    for i in range(0, minimumLength):
        # Get the current character from the first string
        current = strs[0][i]
        # Check if this character is found in all other strings or not
        for j in range(0, len(strs)):
            if strs[j][i] != current:
                return lcp
        lcp += current
    return lcp
strs =  ["flower","flow","flight"]
longestCommonPrefix(strs)

'fl'

In [6]:
def squaredsum(num):
    result = 0
    while(num):
        rem = num%10
        result = result + rem*rem
        num = num//10
    return result

def happynumber(num):
    seen  = set()
    while True:
        num = squaredsum(num)
        if num==1:
            return True
        if num in seen:
            return False
        seen.add(num)

num = int(input("Enter a number: "))
if happynumber(num):
    print(num," is a happy Number")
else:
    print(num," is not a happy number")

Enter a number: 19
19  is a happy Number


In [4]:
#15. 3Sum
"""Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Explanation: 
nums[0] + nums[1] + nums[2] = (-1) + 0 + 1 = 0.
nums[1] + nums[2] + nums[4] = 0 + 1 + (-1) = 0.
nums[0] + nums[3] + nums[4] = (-1) + 2 + (-1) = 0.
The distinct triplets are [-1,0,1] and [-1,-1,2]"""

def threeSum(nums):
    n = len(nums)
    triplets = []
    
    # Sort the array
    nums.sort()           # [-4,-1,-1,0,1,2]
    
    # Fix the first element and find the other two elements
    for i in range(n-2):
        
        # Skip duplicates
        if i > 0 and nums[i] == nums[i-1]:
            continue
        
        # Set the left and right pointers
        left = i + 1
        right = n - 1
        
        while left < right:
            total = nums[i] + nums[left] + nums[right]
            
            if total < 0:
                left += 1
            elif total > 0:
                right -= 1
            else:
                # Found a triplet with sum 0
                triplets.append([nums[i], nums[left], nums[right]])
                
                # Skip duplicates
                while left < right and nums[left] == nums[left+1]:
                    left += 1
                while left < right and nums[right] == nums[right-1]:
                    right -= 1
                
                left += 1
                right -= 1
    
    return triplets

# Example usage
nums = [-1, 0, 1, 2, -1, -4]
result = threeSum(nums)
print(result)


[[-1, -1, 2], [-1, 0, 1]]


In [8]:
def _3sum(num):
    n = len(num)
    num.sort()
    triplets = []
    
    for i in range(n-2):
        if i>0 and num[i]==num[i-1]:
            continue
        left = i + 1
        right = n-1
        
        while left < right:
            total = num[i]+num[left]+num[right]
            if total <0:
                left = left + 1
            elif total > 0:
                right = right -1
            else:
                triplets.append([num[i],num[left],num[right]])
                
                while left < right and num[left]==num[left+1]:
                    left = left + 1
                while left < right and num[right]==num[right-1]:
                    right = right -1
                left = left + 1
                right = right -1
    return triplets
    
    

    
num = [-1, 0, 1, 2, -1, -4]
result = _3sum(num)
print(result)

[[-1, -1, 2], [-1, 0, 1]]


In [33]:
#53.Spiral matrix
import numpy as np
def printSpiral(mat):
    # Define ans array to store the result.
    ans = []
 
    n = len(mat) # no. of rows
    m = len(mat[0]) # no. of columns
  
    # Initialize the pointers reqd for traversal.
    top = 0
    bottom = n - 1
    left = 0
    right = m - 1

    # Loop until all elements are not traversed.
    while (top <= bottom and left <= right):
        # For moving left to right
        for i in range(left, right + 1):
            ans.append(mat[top][i])
        top += 1

        # For moving top to bottom.
        for i in range(top, bottom + 1):
            ans.append(mat[i][right])
        right -= 1

        # For moving right to left.
        if (top <= bottom):
            for i in range(right, left - 1, -1):
                ans.append(mat[bottom][i])
            bottom -= 1

        # For moving bottom to top.
        if (left <= right):
            for i in range(bottom, top - 1, -1):
                ans.append(mat[i][left])
            left += 1
    return ans
#Matrix initialization.
mat = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

print("original list:\n",mat)
                    
ans = printSpiral(mat)

print(ans)

original list:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [25]:
import numpy as np
def spiralmatrix(mat):
    ans = []
    
    n = len(mat)
    m = len(mat[0])
    
    top = 0
    bottom = n-1
    left = 0
    right = m-1
    
    while top<=bottom and left<=right:
        #printing top elements
        for i in range(left,right+1):
            ans.append(mat[top][i])
        top = top + 1
        
        #printing left elements
        for i in range(top,bottom+1):
            ans.append(mat[i][right])
        right = right-1
        
        #printing bottom elemets
        if top<=bottom:
            for i in range(right,left-1,-1):
                ans.append(mat[bottom][i])
            bottom = bottom -1
        
        #printing right elements
        if left <= right:
            for i in range(bottom,top-1,-1):
                ans.append(mat[i][left])
            left = left +1
    return ans
    
    
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original matrix:\n",mat)

res = spiralmatrix(mat)
print(res)

original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 6, 9, 8, 7, 4, 5]


In [50]:
#5. Longest palindromic substring
"""input= 'babad'
output = "bab" or "aba"

input = "cbbd"
output = "bb"
"""

s = "babad"
res = ""
res_len = 0

for i in range(len(s)):
    #odd lenght
    l,r = i,i
    while l>=0 and r<len(s) and s[l]==s[r]:
        if (r-l+1)>=res_len:
            res = s[l:r+1]
            res_len = r-l+1
        l = l -1
        r = r +1 
    #even length
    l,r = i,i+1
    while l>=0 and r<len(s) and s[l]==s[r]:
        if (r-l+1) > res_len:
            res = s[l:r+1]
            res_len = r-l+1
        l = l -1
        r = r+1
print(res)

aba


In [2]:
s = "babad"
rev = s[::-1]
res = ""
for i in range(len(s)):
    if s[i] == rev[i]:
        res = res + s[i]
print(res)

aba


In [4]:
# 1143 Longest Common subsequence of two strings
t1 = "abcde"
t2 = "ace"
m = len(t1)
n = len(t2)

mat = [[0]*(n+1) for z in range(m+1)]
for i in range(m):
    for j in range(n):
        if t1[i] == t2[j]:
            mat[i+1][j+1] = mat[i][j]+1
        else:
            mat[i+1][j+1] = max(mat[i][j+1],mat[i+1][j])
print(mat[-1][-1])
            

3


In [6]:
t1 = "abcde"
t2 = "ace"
t1 = set(t1)
t2 = set(t2)

res = list(t1 & t2)
print(len(res))

3


In [37]:
# 49. Group Anagrams

def group_anagrams(str1):
    dict1 = {}
    for word in str1:
        sorted_word = "".join(sorted(word))
    
        if sorted_word not in dict1:
            dict1[sorted_word] = [word]
        else:
            dict1[sorted_word].append(word)
    ans = []
    for item in dict1.values():
        ans.append(item)
    #return ans
    return dict1

    
str1 = ["eat","tea","tan","ate","nat","bat"]
res = group_anagrams(str1)
print(res)

{'aet': ['eat', 'tea', 'ate'], 'ant': ['tan', 'nat'], 'abt': ['bat']}


In [38]:
#242. Valid Anagram
#Example 1:
#Input: s = "anagram", t = "nagaram"
#Output: true
#Example 2:
#Input: s = "rat", t = "car"
#Output: false

def valid(s,t):
    if len(s) == len(t):
        sorted_s = sorted(s)
        sorted_t = sorted(t)
        if sorted_s == sorted_t:
            print(s,'and',t,'are valid anagrams')
        else:
            print(s,'and',t,'are not valid anagrams')
s = "anagram"
t = "nagaram"
valid(s,t)

anagram and nagaram are valid anagrams


In [39]:
def valid(s,t):
    return sorted(s) == sorted(t)
s = "anagram"
t = "nagaram"
valid(s,t)

True

In [5]:
#26 remove all the duplicates from sorted array
#Input: nums = [1,1,2]
#Output: 2, nums = [1,2,_]

#Input: nums = [0,0,1,1,1,2,2,3,3,4]
#Output: 5, nums = [0,1,2,3,4,_,_,_,_,_]

def remove_dup(nums):
    index = 1
    for i in range(1,len(nums)):
        if nums[i] != nums[i-1]:
            nums[index] = nums[i]
            index = index + 1
    return index

nums = [0,0,1,1,1,2,2,3,3,4]
length = remove_dup(nums)
print(length,nums[:length])

5 [0, 1, 2, 3, 4]


In [5]:
def remove_duplicates(nums):
    return list(set(nums))

nums = [1, 2, 2, 3, 4, 4, 5]
print(remove_duplicates(nums))  # Output order is not guaranteed

[1, 2, 3, 4, 5]


In [7]:
def remove_duplicates(nums):
    seen = set()
    res = []
    
    for num in nums:
        if num not in seen:
            seen.add(num)
            res.append(num)
    return res

nums = [1, 2, 2, 3, 4, 4, 5]
print(remove_duplicates(nums)) 

[1, 2, 3, 4, 5]


In [10]:
def remove_duplicates(nums):
    seen = set()
    return [x for x in nums if not (x in seen or seen.add(x))]

nums = [1, 2, 2, 3, 4, 4, 5]
print(remove_duplicates(nums)) 

[1, 2, 3, 4, 5]


In [11]:
def remove_duplicates(nums):
    return list(dict.fromkeys(nums))

nums = [1, 2, 2, 3, 4, 4, 5]
print(remove_duplicates(nums)) 

[1, 2, 3, 4, 5]


In [19]:
#27 remove element
#Input: nums = [3,2,2,3], val = 3
#Output: 2, nums = [2,2,_,_]

#Input: nums = [0,1,2,2,3,0,4,2], val = 2
#Output: 5, nums = [0,1,4,0,3,_,_,_]

def remove(nums,val):
    count = 0
    while val in nums:
        nums.remove(val)
        count = count + 1
    return len(nums), nums 
    
nums = [3,2,2,3]
val = 3
ans = remove(nums,val)
print(ans)

(2, [2, 2])


In [23]:
#283 move zeros to the end
#Example 1:
#Input: nums = [0,1,0,3,12]
#Output: [1,3,12,0,0]
#Example 2:
#Input: nums = [0]
#Output: [0]

def move_zeros(nums):
    # Initialize an index to keep track of non-zero elements
    non_zero_index = 0
    
    # Iterate through the array
    for i in range(len(nums)):
        # If the current element is non-zero, move it to the non_zero_index position
        if nums[i] != 0:
            nums[non_zero_index] = nums[i]
            non_zero_index += 1
    
    # Fill the remaining part of the array with zeros
    for i in range(non_zero_index, len(nums)):
        nums[i] = 0
        
nums1 = [0, 1, 0, 3, 12]
move_zeros(nums1)
print(nums1)

[1, 3, 12, 0, 0]


In [4]:
#168. Excel Sheet Column Title
#Example 1:
#Input: columnNumber = 1
#Output: "A"
#Example 2:
#Input: columnNumber = 28
#utput: "AB"
#Example 3:
#Input: columnNumber = 701
#Output: "ZY"

def excel_col(col_num):
    col_name = ""
    while col_num > 0:
        rem = (col_num - 1) % 26
        col_name = chr(ord('A') + rem) + col_name
        col_num = (col_num-1) // 26
    return col_name
    
print(excel_col(1))  
print(excel_col(28))  

print(excel_col(701))

A
AB
ZY


In [5]:
#171. Excel Sheet Column Number
#Example 1:
#Input: columnTitle = "A"
#Output: 1
#Example 2:
#Input: columnTitle = "AB"
#Output: 28
#Example 3:
#Input: columnTitle = "ZY"
#Output: 701

def excel_name(col_name):
    col_num = 0
    
    for char in col_name:
        val = ord(char) - ord('A') + 1
        col_num = col_num * 26 + val
    return col_num
    
print(excel_name('A'))  
print(excel_name('AB'))  
print(excel_name('ZY'))

1
28
701


In [1]:
#2194. Cells in a Range on an Excel Sheet
"""Input: s = "K1:L2"
Output: ["K1","K2","L1","L2"]
Explanation:
The above diagram shows the cells which should be present in the list.
The red arrows denote the order in which the cells should be presented.
Example 2:
Input: s = "A1:F1"
Output: ["A1","B1","C1","D1","E1","F1"]
Explanation:
The above diagram shows the cells which should be present in the list.
The red arrow denotes the order in which the cells should be presented."""
def cellsInRange(s):
    start, end = s.split(':')
    res = []
    
    start_col, start_row = start[0], int(start[1:])
    end_col, end_row = end[0], int(end[1:])
    
    for col in range(ord(start_col),ord(end_col)+1):
        for row in range(start_row,end_row+1):
            res.append(chr(col)+str(row))
    return res
    
s = "A1:F1"
cellsInRange(s)

['A1', 'B1', 'C1', 'D1', 'E1', 'F1']

In [4]:
#66. Plus One
#Input: digits = [1,2,3]
#Output: [1,2,4]
#Explanation: The array represents the integer 123.Incrementing by one gives 123 + 1 = 124.Thus, the result should be [1,2,4].

def increment(digits):
    num = 0
    for digit in digits:
        num = num*10 + digit
    num = num +1
    
    res = []
    while num > 0:
        res.insert(0,num%10)
        num = num//10
    return res

digits = [1,2,3]
increment(digits) 
    

[1, 2, 4]

In [8]:
#43. Multiply Strings
#Example 1:
#Input: num1 = "2", num2 = "3"
#Output: "6"
#Example 2:
#Input: num1 = "123", num2 = "456"
#Output: "56088

def multiply(num1,num2):
    x = int(num1)
    y = int(num2)
    res = str(x*y)
    return res
    
num1 = "2"
num2 = "3"
multiply(num1,num2)

'6'

In [34]:
#33. Search in Rotated Sorted Array
#Example 1:
#Input: nums = [4,5,6,7,0,1,2], target = 0
#Output: 4
#Example 2:
#Input: nums = [4,5,6,7,0,1,2], target = 3
#Output: -1
#Example 3:
#Input: nums = [1], target = 0
#Output: -1

def search(nums,target):
    for i in range(len(nums)):
        if nums[i] == target:
            return i
    return -1

nums = [4,5,6,7,0,1,2]
target = 0
search(nums,target)

4